server:
  port: 8801
spring:
  application:
    name: cloud-stream-provider
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: vm129.com
                port: 5672
                username: guest
                password: guest
      bindings:
        output:
          binder: defaultRabbit
          destination: studyExchange
          content-type: application/json
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # 集群
      #      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      # 单机
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: stream-provider8801
    prefer-ip-address: true
management:
  health:
    rabbit:
      enabled: false
