server:
  port: 9527
spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment1
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/**
#            - After=2020-03-15T16:27:47.518211700+08:00[Asia/Shanghai] # get by ZonedDateTime.now()
#            - Before=2020-03-15T16:27:47.518211700+08:00[Asia/Shanghai]
#            - Between=2020-03-15T16:27:47.518211700+08:00[Asia/Shanghai],2020-03-15T17:27:47.518211700+08:00[Asia/Shanghai]
#            - Cookie=username,zyc  #name,value-reg  curl http://localhost:9527/payment/lb --cookie "username=zyc"
#            - Header=X-Resquest-Id,\d+ #name,value-reg curl http://localhost:9527/payment/lb --cookie "username=zyc" -H "X-Resquest-Id:123"
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # 集群
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      # 单机
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: gateway9527
    prefer-ip-address: true
