server:
  port: 80
spring:
  application:
    name: cloud-order-hystrix-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: hystrix-order80
    prefer-ip-address: true
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
logging:
  level:
    std.springcloud.feign.PaymentService: debug
feign:
  hystrix:
    enabled: true
